models:
  - name: KNN
    module: src.model.train
    function: train_knn
    params:
      k: 5

  - name: RF
    module: src.model.train
    function: train_rf
    params:
      n_estimators: 173
      max_depth: 10
      min_samples_split: 10
      min_samples_leaf: 4
      random_state: 42
      n_jobs: -1

  - name: DT
    module: src.model.train
    function: train_dt
    params:
      max_depth: 20
      min_samples_split: 2
      min_samples_leaf: 1
      random_state: 42

  - name: ADABOOST
    module: src.model.train
    function: train_adaboost
    params:
      n_estimators: 100
      learning_rate: 1.0
      loss: 'linear'
      random_state: 42
