models:
  - name: KNN
    module: src.model.train
    function: train_knn
    params:
      k: 5

  - name: RF
    module: src.model.train
    function: train_rf
    params:
      n_estimators: 223
      max_depth: 1
      min_samples_split: 2
      random_state: 42
      n_jobs: -1

  - name: DT
    module: src.model.train
    function: train_dt
    params:
      max_depth: 27
      min_samples_split: 2
      random_state: 42

  - name: ADABOOST
    module: src.model.train
    function: train_adaboost
    params:
      n_estimators: 473
      learning_rate: 0.92
      loss: 'linear'
      random_state: 42

  - name: GBOOST
    module: src.model.train
    function: train_gboost
    params:
      max_depth: 5
      n_estimators: 100
      learning_rate: 1.0
      loss: 'squared_error'
      random_state: 42

